server:
  port: 9091
  servlet:
    context-path: /Book-Store

spring:
  datasource:
    url: jdbc:mysql://bookstore.cleikimg8zt2.eu-north-1.rds.amazonaws.com:3306/bookstore?serverTimezone=UTC
    username: atulpatel
    password: atul1028
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect









