server:
  port: 9090
  servlet:
    context-path: /Book-Store

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/book-store-management-system
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect









